name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Build
        run: ./gradlew build
        env:
          GITHUB_USERNAME: "${{ github.actor }}"
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      - name: Upload package artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Jars
          path: |
            harmony-api/build/libs/*.jar
            harmony-hostswap-agent/build/libs/*.jar
            harmony-sponge/build/libs/*.jar
          if-no-files-found: error
