name: Deploy

on:
  push:
    branches: [ "master" ]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Publish
        run: ./gradlew publishHarmonyPublicationToGitHubPackagesRepository
        env:
          GITHUB_USERNAME: "${{ github.actor }}"
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
